name = "AdventOfCode2020"
uuid = "f792a6b1-e363-4423-8414-76252ea056ad"
authors = ["Sean Smith <scsmithr@gmail.com> and contributors"]
version = "0.1.0"

[deps]
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
IterTools = "c8e1da08-722c-5040-9ed9-7db0dc04731e"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
